{"name": "test_unsuccessful_login_with_invalid_credentials", "status": "broken", "statusDetails": {"message": "pytest_bdd.exceptions.StepDefinitionNotFoundError: Step definition is not found: When \"the user enters invalid credentials\". Line 10 in scenario \"Unsuccessful login with invalid credentials\" in the feature \"F:\\TRAININGS-RECORDING-ALL\\SANJEEV-PYTEST\\tests\\features\\amazon_login.feature\"", "trace": "E   pytest_bdd.exceptions.StepDefinitionNotFoundError: Step definition is not found: When \"the user enters invalid credentials\". Line 10 in scenario \"Unsuccessful login with invalid credentials\" in the feature \"F:\\TRAININGS-RECORDING-ALL\\SANJEEV-PYTEST\\tests\\features\\amazon_login.feature\"\nAll traceback entries are hidden. Pass `--full-trace` to see hidden and internal frames."}, "description": "F:\\TRAININGS-RECORDING-ALL\\SANJEEV-PYTEST\\tests\\features\\amazon_login.feature: Unsuccessful login with invalid credentials", "start": 1727347230418, "stop": 1727347231721, "uuid": "93bdc814-5e73-4b2e-a6c1-087f8fcb1e22", "historyId": "19641b9655ff407128f5d49be5c088a4", "testCaseId": "19641b9655ff407128f5d49be5c088a4", "fullName": "steps.test_amazon_login#test_unsuccessful_login_with_invalid_credentials", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures"}, {"name": "parentSuite", "value": "steps"}, {"name": "suite", "value": "test_amazon_login"}, {"name": "host", "value": "AJAYBONGANI"}, {"name": "thread", "value": "25460-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "steps.test_amazon_login"}]}